name: smart_public_transport_tracker
description: "Smart Public Transport Tracker - BMIT2073 Mobile Application Development"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # State management (simplest option for beginners)
  provider: ^6.1.2

  # Networking
  http: ^1.2.1

  # Maps (OpenStreetMap - free, no API key/billing needed)
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # Location (mobile-unique feature)
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  # GTFS-Realtime protobuf parsing (no need to compile .proto files yourself)
  gtfs_realtime_bindings: 1.2.0

  # Local storage
  shared_preferences: ^2.2.3

  # Parsing the GTFS-Static ZIP feed (routes.txt, stops.txt, etc.)
  archive: ^3.6.1
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
